### ISSUE TITLE
'signature failed'

### ISSUE THREAD

**Issue by dachachacha** [dnet/SudsSigner#2]
This plugin isn't working for me. I converted a JKS keystore to a PEM file containing the certificate and the private key. I'm passing the password in pwd. But all I'm getting is the 'signature failed' error. 

Any idea how I can troubleshoot this?
Many thanks
dkenna

**Comment by dnet** [comment]
Could you post a full stack trace if you have one? Also, it would help if I could see your code (without sensitive parts of course), you can upload it to gist.github.com and post the link here.

**Comment by dachachacha** [comment]
Thanks for your reply. I'm a newbie at certificates and signatures. 
We're using what we call a soft token in a jks format. I used the following procedure to convert it to a pem: http://hublog.hubmed.org/archives/001806.html

stack trace: https://gist.github.com/dkenna/c2b35ecb06af80d562e1
code: https://gist.github.com/dkenna/b0f5d9b5f599314ca407

Many thanks for your help!

**Comment by rsdouglas** [comment]
I'm also experiencing a signature failed error - any idea what would cause this?

```
func=xmlSecTransformNodeRead:file=transforms.c:line=1543:obj=unknown:subj=xmlSecTransformIdListFindByHref:error=1:xmlsec library function failed:href=rsa
func=xmlSecTransformCtxNodeRead:file=transforms.c:line=694:obj=unknown:subj=xmlSecTransformNodeRead:error=1:xmlsec library function failed:name=SignatureMethod
func=xmlSecDSigCtxProcessSignedInfoNode:file=xmldsig.c:line=742:obj=unknown:subj=xmlSecTransformCtxNodeRead:error=1:xmlsec library function failed:node=SignatureMethod
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=547:obj=unknown:subj=xmlSecDSigCtxProcessSignedInfoNode:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxSign:file=xmldsig.c:line=303:obj=unknown:subj=xmlSecDSigCtxSigantureProcessNode:error=1:xmlsec library function failed: 
ERROR:suds.plugin:signature failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/suds/plugin.py", line 254, in __call__
    method(ctx)
  File "*********************/SudsSigner/plugin.py", line 70, in sending
    context.envelope = self.get_signature(etree.tostring(env))
  File "**************/SudsSigner/plugin.py", line 106, in get_signature
    raise RuntimeError('signature failed')
RuntimeError: signature failed
```

**Comment by dnet** [comment]
If you look at the source, this exception gets thrown when the `sign()` method of the xmlsec context is called, so something goes wrong inside there. What OS are you using? If GNU/Linux, what distribution? How did you install xmlsec? Did you have any options that would've allowed selecting a crypto backend such as OpenSSL or GnuTLS? If so, which did you choose?

**Comment by rsdouglas** [comment]
Thanks for the response!
I'm using xubuntu - 3.11.0-26-generic #45-Ubuntu SMP Tue Jul 15 04:02:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I installed xmlsec from https://github.com/dnet/pyxmlsec.git

When prompted for a crypto backend I selected OpenSSL

**Comment by dnet** [comment]
Can you try selecting GnuTLS and see if it improves the situation? If not, please create a minimal working example I can try (so that it includes keys and WSDLs and URLs that can be published). It would not only help me debug the problem, but also if it starts working while you replace your actual/production/secret parts (keys, WSDLs, URLs), you'll know where we should look.

**Comment by rsdouglas** [comment]
Ok, I got a different error with GnuTLS. I'll get the minimal example up somewhere.

```
func=xmlSecGCryptAppKeyLoadMemory:file=app.c:line=232:obj=unknown:subj=xmlSecGCryptAppKeyLoadMemory:error=9:feature is not implemented: 
func=xmlSecGCryptAppKeyLoad:file=app.c:line=176:obj=unknown:subj=xmlSecGCryptAppKeyLoadMemory:error=1:xmlsec library function failed:filename=certs/both.pem
ERROR:suds.plugin:'xmlSecCryptoAppKeyLoad() failed'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/suds/plugin.py", line 254, in __call__
    method(ctx)
  File "*****/SudsSigner/plugin.py", line 70, in sending
    context.envelope = self.get_signature(etree.tostring(env))
  File "*****/SudsSigner/plugin.py", line 104, in get_signature
    with XmlSecSignatureContext(self) as dsig_ctx:
  File "*****/SudsSigner/xmlsec_wrapper.py", line 10, in __init__
    self.dsig_ctx.signKey = get_xmlsec_keyfile(plugin)
  File "*****/SudsSigner/xmlsec_wrapper.py", line 21, in get_xmlsec_keyfile
    plugin.pwdCallbackCtx)
  File "/usr/local/lib/python2.7/dist-packages/xmlsec.py", line 458, in cryptoAppKeyLoad
    if ret is None: raise Error('xmlSecCryptoAppKeyLoad() failed')
Error: 'xmlSecCryptoAppKeyLoad() failed'
111
```

**Comment by rsdouglas** [comment]
Minimal example:
https://gist.github.com/rsdza/064ac38cc8173698380d

I haven't done any work with suds or x509 certs before today, so it could be a very basic error on my part.

I generated the key and cert file with this command:
openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 3650 -nodes

And them simply combined the two resulting files into both.pem

**Comment by dnet** [comment]
Thanks, I managed to reproduce the issue using GnuTLS, I'll investigate. Also, it's worth checking that the server response said

```
Server raised fault: 'These policy alternatives can not be satisfied:
...
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}EncryptedParts: {http://schemas.xmlsoap.org/soap/envelope/}Body not ENCRYPTED
```

If the service really expects the response to be encrypted, you'd be in trouble since SudsSigner can only sign SOAP messages, but not encrypt it. Did you look into this?

**Comment by rsdouglas** [comment]
Ah - I didn't realise it only signs it.

Thanks for looking into this. I'll probably have to find a different service provider with a less cumbersome API.
